package main

// Which installation an agent integration belongs to.
//
// Two installations on one machine share a binary whenever the second was set
// up by running the first's copy — `~/.tokendrop/bin/dropin-miner setup -home
// ~/dm-disposable` is the documented way to make one. v0.2.9 decided a hook
// entry, an allow rule or a skill was "ours" by its BINARY PATH alone, so
// uninstalling either installation planned the removal of both installations'
// integrations: every entry ran the same binary, so every entry matched (#73,
// soak row S20). The shell-profile block was already right — it is matched by
// the config it names, and the disposable run left the soak's block alone and
// said why.
//
// So the rule is the profile block's, applied everywhere: an integration is
// this installation's only when it runs one of this installation's binaries
// AND names this installation's resolved config. Anything else is another
// installation's, and is left and reported rather than removed.
//
// The spellings are generated by the same renderers install writes with
// (shell_commands.go), not enumerated by hand here, so what uninstall
// recognizes is what install wrote on that OS by construction. The one
// spelling not from a renderer is Go's %q, which is v0.2.9's and is kept
// because an installation that upgraded still carries it until the next
// `agents install`.

import (
	"path/filepath"
	"strconv"
	"strings"
)

// installationRef is one installation, as ownership is decided against it:
// the binaries whose integrations it may own, and the resolved config its
// own integrations name. cfg is empty only for an installation running on
// discovery, which writes commands with no -config at all.
type installationRef struct {
	bins []string
	cfg  string
}

func refFor(entry binEntry) installationRef {
	return installationRef{bins: []string{entry.command}, cfg: entry.cfg}
}

// binaryPrefixes is every spelling of `<bin> ` this client has written: the
// three shells' quoting from H2 and H3, v0.2.9's %q, and the bare path.
// PowerShell's carries the call operator, because that is what the renderer
// emits and a command without it is an expression, not a call (#69).
func binaryPrefixes(bin string) []string {
	return []string{
		posixQuoteArg(bin) + " ",
		"& " + powerShellQuoteArg(bin) + " ",
		`"` + bin + `" `,
		strconv.Quote(bin) + " ",
		bin + " ",
	}
}

// afterBinary strips the leading binary from a rendered command and returns
// what follows, or false when the command runs none of this installation's
// binaries.
func (ref installationRef) afterBinary(command string) (string, bool) {
	for _, bin := range ref.bins {
		for _, prefix := range binaryPrefixes(bin) {
			if strings.HasPrefix(command, prefix) {
				return command[len(prefix):], true
			}
		}
	}
	return "", false
}

// renderedWords splits a rendered command into words, keeping a quoted word
// whole. It is not a shell parser and must not become one: it understands
// exactly the quoting this client renders — a single-quoted word (POSIX and
// PowerShell), a double-quoted word (cmd and %q), and a bare word — which is
// enough to find one flag's argument in a command we wrote ourselves.
func renderedWords(s string) []string {
	var words []string
	i := 0
	for i < len(s) {
		for i < len(s) && s[i] == ' ' {
			i++
		}
		if i >= len(s) {
			break
		}
		// A word ends at the first space that is not inside quotes — stated
		// that way rather than as "a quoted run", because both single-quote
		// escapes put a quote straight back after closing one: POSIX spells
		// an embedded quote '\'' and PowerShell spells it ''. A scanner that
		// stopped at the first closing quote would cut '/home/it'\''s/x' into
		// three words and never reach the flag after it.
		start := i
		quote := byte(0)
		for i < len(s) {
			c := s[i]
			if quote == '"' && c == '\\' && i+1 < len(s) {
				i += 2 // a %q escape: the next byte is literal, a quote included
				continue
			}
			if quote == 0 {
				if c == ' ' {
					break
				}
				// POSIX spells an embedded quote by closing the run and
				// writing \' outside it, so this backslash-quote is a literal
				// character and emphatically not the start of a new quoted
				// run. Narrowed to a following quote on purpose: a bare
				// Windows path is full of backslashes that escape nothing.
				if c == '\\' && i+1 < len(s) && (s[i+1] == '\'' || s[i+1] == '"') {
					i += 2
					continue
				}
				if c == '\'' || c == '"' {
					quote = c
				}
			} else if c == quote {
				quote = 0
			}
			i++
		}
		words = append(words, s[start:i])
	}
	return words
}

// unquoteRenderedPath is the path a rendered word names. It returns every
// reading the word may have, because a double-quoted word is ambiguous: cmd
// strips the quotes and takes the rest literally, while %q escapes, and a
// Windows path spelled either way names the same file.
func unquoteRenderedPath(word string) []string {
	if len(word) < 2 {
		return []string{word}
	}
	switch word[0] {
	case '\'':
		if word[len(word)-1] != '\'' {
			return []string{word}
		}
		raw := word[1 : len(word)-1]
		return []string{strings.ReplaceAll(raw, `'\''`, "'"), strings.ReplaceAll(raw, "''", "'")}
	case '"':
		if word[len(word)-1] != '"' {
			return []string{word}
		}
		out := []string{word[1 : len(word)-1]}
		if u, err := strconv.Unquote(word); err == nil && u != out[0] {
			out = append(out, u)
		}
		return out
	}
	return []string{word}
}

// namesOurConfig: does what follows the binary name this installation's
// config? An installation running on discovery wrote no -config at all, so
// for it the absence of the flag is the match and its presence is another
// installation's.
//
// The comparison is samePath, not bytes: v0.2.9's %q hands Windows a path
// with doubled separators naming the same file, and Windows paths differ in
// case without differing.
func (ref installationRef) namesOurConfig(rest string) bool {
	words := renderedWords(rest)
	for i, w := range words {
		if w != "-config" || i+1 >= len(words) {
			continue
		}
		if ref.cfg == "" {
			return false
		}
		for _, cand := range unquoteRenderedPath(words[i+1]) {
			if samePath(cand, ref.cfg) {
				return true
			}
		}
		return false
	}
	return ref.cfg == ""
}

// commandIsOurs is the whole rule in one line: this installation's binary,
// this installation's config.
func (ref installationRef) commandIsOurs(command string) bool {
	rest, ok := ref.afterBinary(command)
	if !ok {
		return false
	}
	return ref.namesOurConfig(rest)
}

// ── the one integration that names directories ──────────────────────────

// codexBlockOwner answers, for our marked block in Codex's config.toml, the
// question commandIsOurs answers for everything else: is this integration
// this installation's, and if not, whose?
//
// The block runs no command, so it names no binary and no config. What it
// names is DIRECTORIES — the roots a sandboxed search must be able to write —
// so the roots are the reading, and they are attributed against the
// directories this installation's config NAMES: state_dir, spool_dir,
// intake_dir and sessions_dir, compared as paths (codexOwnedRoots). Every
// root in the block must be one of them.
//
// They are config keys, not a layout, and that is the whole correction here.
// The first version of this asked whether every root lay under the directory
// holding the config, which is true of the default layout and of nothing
// else: a participant whose state_dir points outside their tokendrop home has
// a block their own install wrote and could then no longer recognize, so the
// refresh their config change had just made necessary printed "it belongs to
// another installation" and did nothing, and their uninstall left it. The
// home-prefix reading survives only in describeSandboxOwner, to DESCRIBE a
// block that is somebody else's — never to decide whether one is ours.
//
// A partial match is not a match: the renderer writes one config's roots as
// one list, so a block holding some of ours and some of another
// installation's is not one this installation wrote, and rewriting it would
// replace roots another installation's searches depend on. Left and named is
// recoverable by hand; replaced is a Codex that earns nothing and says
// nothing (#128).
//
// Two cases answer "not ours" without naming an owner, because neither can be
// attributed at all: a block with no readable roots, and an installation
// whose config cannot be read. The second is new with this reading and is the
// safe direction — a block left is recoverable, a block taken from another
// installation is not — and the sentence says which of the two it was.
//
// Discovery — an installation running with no config at all — has nothing to
// compare against, and v0.2.9 wrote the block from whatever config it found,
// so it keeps the block rather than strand one nothing can attribute.
func codexBlockOwner(ourTable string, entry binEntry, getenv func(string) string) (ours bool, other, why string) {
	if entry.cfg == "" {
		return true, "", ""
	}
	roots := markedSandboxRoots(ourTable)
	if len(roots) == 0 {
		return false, "", "its writable roots cannot be read, so it cannot be attributed to this installation"
	}
	owned := codexOwnedRoots(entry, getenv)
	if len(owned) == 0 {
		return false, "", "this installation's own config cannot be read, so the directories to compare its roots against are unknown"
	}
	for _, r := range roots {
		if !dirsInclude(owned, r) {
			return false, describeSandboxOwner(roots), ""
		}
	}
	return true, "", ""
}

// dirsInclude asks whether one directory is among a set of them, as paths:
// v0.2.9's %q hands Windows a path with doubled separators naming the same
// directory, and Windows paths differ in case without differing — the same
// reason namesOurConfig compares with samePath rather than bytes.
func dirsInclude(dirs []string, dir string) bool {
	for _, d := range dirs {
		if samePath(d, dir) {
			return true
		}
	}
	return false
}

// describeSandboxOwner names the installation a block's roots belong to, in
// the words describeOther uses for every other artifact — so a host whose
// skill and whose block are both another installation's is told about in one
// sentence, not two (noteOnce collapses them).
//
// This is the ONLY thing the home-prefix reading is for. The block has already
// been decided not to be ours, by the directories our own config names, and
// all that is left is to say something useful about whose it is; a guess that
// is merely likely is the right kind of answer to that question and the wrong
// kind to "may this be rewritten".
//
// The home is the deepest directory every root lies under, and it is called
// an installation only when a config is actually there: the block names
// directories, and a directory holding no tokendrop.toml is a place, not an
// installation. Roots with no common home short of the filesystem root name
// nobody, and the sentence says that rather than pointing at "/".
func describeSandboxOwner(roots []string) string {
	home := commonParentDir(roots)
	if home == "" {
		return "another installation"
	}
	if cfg := filepath.Join(home, setupConfigFile); lexists(cfg) {
		return "the installation configured by " + displayNamedPath(cfg)
	}
	return "the installation under " + displayNamedPath(home)
}

// commonParentDir is the deepest directory every path lies strictly under, or
// "" when that would be the filesystem root.
//
// It walks up asking pathUnder, the same ancestor test the attribution itself
// uses, rather than comparing path text: a prefix taken by bytes would put
// /home/user-two under /home/user, and the two readings must not disagree
// about what "under" means.
func commonParentDir(paths []string) string {
	if len(paths) == 0 {
		return ""
	}
	dir := filepath.Dir(filepath.Clean(paths[0]))
	for {
		if parent := filepath.Dir(dir); parent == dir {
			return "" // the filesystem root names no installation
		}
		covers := true
		for _, p := range paths {
			if samePath(p, dir) || !pathUnder(p, dir) {
				covers = false
				break
			}
		}
		if covers {
			return dir
		}
		dir = filepath.Dir(dir)
	}
}
